name: Executar script diariamente

on:
  schedule:
    - cron: "0 12 * * *"  # Roda às 9h (horário de Brasília = UTC-3)
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar script principal
        env:
          TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          HOSTNAME: ${{ secrets.DATABRICKS_HOSTNAME }}
          HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          TICKERS: ${{ secrets.TICKERS }}
          TOKEN_BRAPI: ${{ secrets.TOKEN_BRAPI }}
        run: |
          python ./02_preco_cotas.py
